language: php

matrix:
  fast_finish: true
  include:
    - env: DBTYPE=sqlite
      php: 5.5
    - env: DBTYPE=mysql
      php: hhvm
    - env: DBTYPE=sqlite
      php: hhvm

sudo: false

install: travis_retry composer install

script: phpunit
